### ISSUE TITLE
Crash when using a casted mram pointer

### ISSUE THREAD

**Issue by JordiChauzi** [upmem/llvm#1]
The following code crashes clang:

```c
#include <stdlib.h>
 #include <mram.h>

 #define TASKLETS_INITIALIZER TASKLET(main, 1024, 0)
 #include <rt.h>

 char __mram_keep toto[255];

 int main(void) {
     *((char *) toto) = 0x2a;

     return EXIT_SUCCESS;
 }
```

Because of the line ` *((char *) toto) = 0x2a;`.

Clash report:

> fatal error: error in backend: Cannot select: 0x563c48a23810: i32 = addrspacecast[255 -> 0] 0x563c48a23948
>   0x563c48a23948: i32 = DPUISD::Wrapper TargetGlobalAddress:i32<[255 x i8] addrspace(255)* @toto> 0
>     0x563c48a23740: i32 = TargetGlobalAddress<[255 x i8] addrspace(255)* @toto> 0
> In function: main
> clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
> clang version 7.1.0 (git@github.com:upmem/clang.git 8e2c3063c7ce02f2b04eb24723e66f6d2d1dcf9f) (git@github.com:upmem/llvm.git 9dce7c18aca061ccfe4fc28a253ae320274a0dfb)
> Target: dpu-upmem-dpurte
> Thread model: posix
> InstalledDir: /home/jchauzi/package-sdk-current/upmem-internal/usr/bin

**Comment by ghost** [comment]
I've managed to have a cleaner message but no debug information on the file and line, so it is not enough.
I've sent a message on LLVM-dev mailing list. I'll push what I have if this mail does not give us a better solution.
