### ISSUE TITLE
optimize generated instructions with lsl_add

### ISSUE THREAD

**Issue by vpalatin** [upmem/llvm#18]
When compiling the following code :
```
#include <stdint.h>

uint32_t dup(uint8_t c) {
    return c + (c << 8);
}
```
I'm getting the following sequence:
```
lsl r1, r0, 8
or r0, r0, r1
```
which could be optimized in a single lsl_add

At the end of the day, I'm interested in getting a more optimized sequence for :  
```
uint32_t memset32(int c) {
    uint8_t v = c;
    return v | (v << 8) | (v << 16) | (v << 24) ;
}
```

**Comment by ghost** [comment]
https://github.com/upmem/llvm/blob/upmem_release_80/lib/CodeGen/SelectionDAG/DAGCombiner.cpp#L2160

**Comment by ghost** [comment]
```
memset32:                               // @memset32
// %bb.0:
	and r1, r0, 255
	lsl r0, r0, 24
	or r0, r0, r1
	lsl_add r0, r0, r1, 8
	lsl_add r0, r0, r1, 16
	jump r23
```
WDYT @vpalatin ?

**Comment by vpalatin** [comment]
Why not the simpler version ? 
(if both source regs can be identical, the asm seems happy with it)
```
memset32better:                              
	and r0, r0, 255
	lsl_add r0, r0, r0, 8
	lsl_add r0, r0, r0, 16
	jump r23
```

**Comment by ghost** [comment]
new version!

```
memset32:                               // @memset32
// %bb.0:
	and r1, r0, 255
	lsl_add r0, r1, r0, 24
	lsl_add r0, r0, r1, 8
	lsl_add r0, r0, r1, 16
	jump r23
```

**Comment by ghost** [comment]
We don't have the best version, but it seems that it is not due to the backend. Should we close this issue?

**Comment by vpalatin** [comment]
And we have an ... automated test !
So we can close
